port: 8080
logLevel: debug #info, debug
mysql:
  addr: 127.0.0.1:3306
  user: root
  password: 123456
  database: message_bot
  maxidleconns: 10
  maxopenconns: 100

tgBot:
  token: token-23 #token
  debug: true
  timeout: 20